# Generated by Django 5.2 on 2025-04-06 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrationmanagement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseregistration",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_registration",
                to="registrationmanagement.course",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Student", "Student"),
                    ("Faculty", "Faculty"),
                    ("Admin", "Admin"),
                ],
                default="Student",
                max_length=20,
            ),
        ),
    ]
